name: Deploy gh-pages
on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      # - name: eslint
      #   run: npm run lint

      # - name: coverage
      #   run: npm run coverage

      - name: build:docs
        run: npm run build:docs

      # - name: moveCoverage
      #   run: sh ./scripts/mv-coverage.sh

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GIT_KEY }}
          BRANCH: gh-pages
          FOLDER: ./docs-dist
